#!/bin/sh

git filter-branch -f --env-filter '

an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"

if [ "$GIT_COMMITTER_EMAIL" = "s.k.golovin@gmail.com" ]
then
    cn="IntegralTeam"
    cm="repo@sfxdx.ru"
fi
if [ "$GIT_AUTHOR_EMAIL" = "s.k.golovin@gmail.com" ]
then
    an="IntegralTeam"
    am="repo@sfxdx.ru"
fi

export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
'
