.TH "event2 Directory Reference" 3 "Fri Sep 15 2017" "libevent" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event2 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuffer\&.h\fP"
.br
.RI "Functions for buffering data for network sending or receiving\&. "
.ti -1c
.RI "file \fBbuffer_compat\&.h\fP"
.br
.RI "Obsolete and deprecated versions of the functions in \fBbuffer\&.h\fP: provided only for backward compatibility\&. "
.ti -1c
.RI "file \fBbufferevent\&.h\fP"
.br
.RI "Functions for buffering data for network sending or receiving\&. "
.ti -1c
.RI "file \fBbufferevent_ssl\&.h\fP"
.br
.RI "OpenSSL support for bufferevents\&. "
.ti -1c
.RI "file \fBdns\&.h\fP"
.br
.RI "Welcome, gentle reader\&. "
.ti -1c
.RI "file \fBdns_compat\&.h\fP"
.br
.RI "Potentially non-threadsafe versions of the functions in \fBdns\&.h\fP: provided only for backwards compatibility\&. "
.ti -1c
.RI "file \fBevent\&.h\fP"
.br
.RI "Core functions for waiting for and receiving events, and using event bases\&. "
.ti -1c
.RI "file \fBevent_compat\&.h\fP"
.br
.RI "Potentially non-threadsafe versions of the functions in \fBevent\&.h\fP: provided only for backwards compatibility\&. "
.ti -1c
.RI "file \fBhttp\&.h\fP"
.br
.RI "Basic support for HTTP serving\&. "
.ti -1c
.RI "file \fBhttp_compat\&.h\fP"
.br
.RI "Potentially non-threadsafe versions of the functions in \fBhttp\&.h\fP: provided only for backwards compatibility\&. "
.ti -1c
.RI "file \fBrpc\&.h\fP"
.br
.RI "This header files provides basic support for an RPC server and client\&. "
.ti -1c
.RI "file \fBrpc_compat\&.h\fP"
.br
.RI "Deprecated versions of the functions in \fBrpc\&.h\fP: provided only for backwards compatibility\&. "
.ti -1c
.RI "file \fBtag\&.h\fP"
.br
.RI "Helper functions for reading and writing tagged data onto buffers\&. "
.ti -1c
.RI "file \fBtag_compat\&.h\fP"
.br
.RI "Obsolete/deprecated functions from \fBtag\&.h\fP; provided only for backwards compatibility\&. "
.ti -1c
.RI "file \fBthread\&.h\fP"
.br
.RI "Functions for multi-threaded applications using Libevent\&. "
.ti -1c
.RI "file \fButil\&.h\fP"
.br
.RI "Common convenience functions for cross-platform portability and related socket manipulations\&. "
.in -1c
