#!/bin/bash
mkdir -p ~/.crypticcoin-params
cp /usr/lib/crypticcoin-wallet/resources/sprout* ~/.crypticcoin-params



mkdir -p ~/.crypticcoin
if [ -e ~/.crypticcoin/crypticcoin.conf ]; then
    cp -a ~/.crypticcoin/crypticcoin.conf ~/.crypticcoin/crypticcoin.bak
fi

mkdir -p ~/.crypticcoin/tor_exe
cp /usr/lib/crypticcoin-wallet/resources/tor ~/.crypticcoin/tor_exe

echo -e "rpcuser="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 26 ; echo '')"\n""rpcpassword="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 26 ; echo '')"\n""rpcport=23202""\n""port=23303""\n""daemon=0""\n""listen=1""\n""server=1""\n""rpcallowip=127.0.0.1""\n""tor_exe_path=~/.crypticcoin/tor_exe/tor""\n""proxy=127.0.0.1:9089""\n""bind=127.0.0.1""\n""addnode=2yt4fstq5oacwwh5.onion"> ~/.crypticcoin/crypticcoin.conf

chown -R $SUDO_USER:$SUDO_USER ~/.crypticcoin/crypticcoin.conf

cp /usr/lib/crypticcoin-wallet/resources/crypticcoin.desktop /home/$SUDO_USER/Desktop/

chmod +x /home/$SUDO_USER/Desktop/crypticcoin.desktop

echo "Exit"
