#!/bin/bash
mkdir -p $HOME/.crypticcoin-params
cp /usr/lib/crypticcoin-wallet/resources/sprout* $HOME/.crypticcoin-params

chown -R $SUDO_USER:$SUDO_USER ~/.crypticcoin-params

mkdir -p $HOME/.crypticcoin
if [ -e $HOME/.crypticcoin/crypticcoin.conf ]; then
	cp -a $HOME/.crypticcoin/crypticcoin.conf $HOME/.crypticcoin/crypticcoin.bak
fi

mkdir -p $HOME/.crypticcoin/tor_exe
cp /usr/lib/crypticcoin-wallet/resources/tor $HOME/.crypticcoin/tor_exe

echo -e "rpcuser="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 26 ; echo '')"\n""rpcpassword="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 26 ; echo '')"\n""rpcport=23202""\n""port=23303""\n""daemon=0""\n""listen=1""\n""server=1""\n""rpcallowip=127.0.0.1/8""\n""tor_exe_path=/home/"`logname`"/.crypticcoin/tor_exe/tor""\n""onlynet=onion""\n""bind=127.0.0.1""\n""addnode=5wa52xtesl4yjnhp.onion:23303""\n""addnode=axjnhxwkhaqle7dh.onion:23303"> $HOME/.crypticcoin/crypticcoin.conf

chown -R $SUDO_USER:$SUDO_USER ~/.crypticcoin/

cp /usr/lib/crypticcoin-wallet/resources/crypticcoin.desktop ~/.local/share/applications/

echo `logname`

echo "Exit"
